- projects/ama-sdk/src/lib/api-implementations/aps-api/entity.factory.ts
- projects/ama-sdk/src/lib/api/public_api.ts
- projects/ama-sdk/src/lib/helpers/create-entries-names.ts
- src/app/application-editor/store/effects/empty-diagram.spec.ts
- src/app/application-editor/store/effects/empty-diagram.ts
- src/app/process-editor/services/bpmn-js/property-handlers/calledElement.handler.ts
- src/app/process-editor/services/bpmn-js/property-handlers/calledElemet.handler.spec.ts
- src/app/process-editor/services/bpmn-js/property-handlers/process-variables.handler.ts
- src/app/process-editor/services/bpmn-js/property-handlers/property.handlers.ts
- src/app/process-editor/services/bpmn/elements-properties.ts
- src/app/process-editor/services/bpmn/properties.ts
- src/app/process-editor/services/cardview-properties/bpmn2CardView.ts
- src/app/process-editor/services/cardview-properties/calledElement-cardview-property.ts
- src/app/process-editor/store/process-editor.selectors.ts
> - [x] Bugfix
Lack of process variables, CallActivity related issues.
Implemented …
> Latest patches 2018-12

- projects/ama-sdk/src/lib/api-implementations/acm-api/application-api.ts
> - [ ] Bugfix
'applications' endpoints is used
'projects' endpoints is used
**Does …
> [APM-695] Change 'applications' endpoint to 'projects'

- projects/ama-sdk/src/lib/api-implementations/acm-api/model-api.ts
> - [ ] Bugfix
'applications' endpoints is used
'projects' endpoints is used
**Does …
> [APM-695] Forgotten api modification for models

- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/connector-editor/connector-editor.selectors.spec.ts
- projects/ama-sdk/src/lib/connector-editor/connector-editor.selectors.ts
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.html
- projects/ama-sdk/src/lib/helpers/directives/allowed-characters.directive.spec.ts
- projects/ama-sdk/src/lib/helpers/directives/allowed-characters.directive.ts
- projects/ama-sdk/src/lib/helpers/public_api.ts
- projects/ama-sdk/src/lib/helpers/shared.module.ts
- projects/ama-sdk/tslint.json
- tslint.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-704
Done
**Does this PR …
> [APM-704] Model's naming restriction applied for creation and connector edition

- src/app/process-editor/components/process-modeler/palette.ts
- src/app/process-editor/components/process-modeler/process-modeler-bpmnjs.component.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-705
Intermediate event was …
> [APM-705] Remove unnecessary Start and End Events

- src/app/process-editor/store/process-editor.actions.ts
- src/app/process-editor/store/process-editor.effects.spec.ts
- src/app/process-editor/store/process-editor.effects.ts
- src/app/process-editor/store/process-entities.reducer.spec.ts
- src/app/process-editor/store/process-entities.reducer.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-717
Fixed
**Does this PR …
> [APM-717] Process update fix

- resources/i18n/en.json
> - [ ] Bugfix
> - [x] Other... Please describe: translate strings
**Does this PR introduce a breaking change?** (check …
> [APM-650] new translate strings

- projects/ama-sdk/src/lib/connector-editor/connector-editor.selectors.ts
- projects/ama-sdk/src/lib/store/app.selectors.ts
- projects/ama-sdk/src/lib/store/app.state.ts
- src/app/connector-editor/services/connector-editor.service.ts
- src/app/connector-editor/store/connector-editor.effects.spec.ts
- src/app/connector-editor/store/connector-editor.effects.ts
- src/app/process-editor/store/process-editor.effects.ts
- src/app/project-editor/components/project-navigation/project-navigation.component.html
- src/app/project-editor/components/project-navigation/project-navigation.component.ts
- src/app/project-editor/components/project-tree/project-tree-module-filter/project-tree-filter.component.spec.ts
- src/app/project-editor/components/project-tree/project-tree.component.html
- src/app/project-editor/components/project-tree/project-tree.component.spec.ts
- src/app/project-editor/components/project-tree/project-tree.component.ts
- src/app/project-editor/components/upload-file-button/upload-file-button.component.spec.ts
- src/app/store/reducers/app.reducer.ts
- src/app/store/states/app.state.ts
> - [ ] Bugfix
> - [x] Code style update (formatting, local variables)
https://issues.alfresco.com/jira/browse/APM-696
done
**Does this PR …
> [APM-696] Application to Project

- resources/i18n/en.json
- src/app/connector-editor/store/connector-editor.effects.spec.ts
- src/app/connector-editor/store/connector-editor.effects.ts
- src/app/process-editor/store/process-editor.effects.spec.ts
- src/app/process-editor/store/process-editor.effects.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-543
done
**Does this PR …
> [APM-543] Custom message for uploading models

- projects/ama-sdk/src/lib/interfaces/model-creator.interface.ts
- resources/i18n/en.json
- src/app/connector-editor/extension/connector-creator.extension.ts
- src/app/process-editor/extension/process-creator.extension.ts
- src/app/project-editor/components/project-navigation/project-navigation.component.html
- src/app/project-editor/components/project-navigation/project-navigation.component.scss
- src/app/project-editor/components/project-navigation/project-navigation.component.spec.ts
- src/app/project-editor/components/upload-file-button/upload-file-button.component.html
- src/app/project-editor/components/upload-file-button/upload-file-button.component.scss
- src/app/project-editor/components/upload-file-button/upload-file-button.component.spec.ts
- src/app/project-editor/components/upload-file-button/upload-file-button.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-718
**What is the new behavior?**
Done
**Does this PR …
> [APM-718] New dropdown structure

- resources/i18n/en.json
> - [ ] Bugfix
> - [] Feature
> - [ ] Other... Please describe: translate strings
https://issues.alfresco.com/jira/browse/APM-714
**Does …
> [APM-714] new translate strings for ui advanced editor

- src/app/process-editor/store/process-editor.selectors.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-722
fixed
**Does this PR …
> [APM-722] fix process filter loading

- src/app/project-editor/components/upload-file-button/upload-file-button.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-711
Fixed
**Does this PR …
> [APM-711] Edit button css fix

- src/app/process-editor/services/bpmn-js/property-handlers/formSelector.handler.ts
- src/app/process-editor/services/bpmn-js/property-handlers/implementation.handler.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-723
fixed
**Does this PR …
> [APM-723] Bpmn xml fix

- src/app/project-editor/components/project-navigation/project-navigation.component.html
- src/app/project-editor/components/project-navigation/project-navigation.component.spec.ts
- src/app/project-editor/components/project-tree/project-tree-module-filter/project-tree-filter.component.html
> - [ ] Bugfix
> - [x] Other... Please describe: Add UI locators for e2e tests
**Does this PR introduce a breaking …
> [APM-712] Add UI locators for e2e tests

- src/app/connector-editor/store/connector-editor.effects.ts
> - [x] Bugfix
no-jirra issue
**Does this PR introduce a breaking change?** (check one …
> fix bug on delete connectors

- resources/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-636
added new translation …
> [APM-636] new translate strings

- projects/ama-sdk/src/lib/helpers/unsaved-page.guard.ts
- projects/ama-sdk/src/lib/store/app.selectors.ts
- resources/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-318
done
**Does this PR …
> [APM-318] Custom confirmation messages for unsaved-page.guard

- projects/ama-sdk/src/lib/api-implementations/acm-api/model-api.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-691
the error no longer …
> [APM-691] removed angular error

- projects/ama-sdk/src/lib/confirmation-dialog/components/confirmation-dialog/confirmation-dialog.component.html
- projects/ama-sdk/src/lib/confirmation-dialog/components/confirmation-dialog/confirmation-dialog.component.spec.ts
- projects/ama-sdk/src/lib/confirmation-dialog/components/confirmation-dialog/confirmation-dialog.component.ts
- projects/ama-sdk/src/lib/helpers/unsaved-page.guard.ts
- projects/ama-sdk/src/lib/store/app.selectors.ts
- resources/i18n/en.json
- src/app/connector-editor/components/connector-header/connector-header.component.spec.ts
- src/app/connector-editor/components/connector-header/connector-header.component.ts
- src/app/connector-editor/store/connector-editor.actions.ts
- src/app/connector-editor/store/connector-editor.effects.ts
- src/app/dashboard/components/projects-list/projects-list.component.ts
- src/app/process-editor/components/process-editor/process-editor.component.spec.ts
- src/app/process-editor/components/process-editor/process-editor.component.ts
- src/app/process-editor/store/process-editor.actions.ts
- src/app/process-editor/store/process-editor.effects.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-694
done
**Does this PR …
> [APM-694] Custom confirmation messages for save/download model

- src/app/app.routes.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-658
added adf about-page …
> [APM-658] added about page

- src/app/connector-editor/components/connector-editor/connector-editor.component.scss
- src/app/project-editor/components/project-tree/project-tree-module-filter/project-tree-filter.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-732
fixed
**Does this PR …
> [APM-732] Firefox bugs fix

- src/app/connector-editor/components/connector-editor/connector-editor.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-730
fixed
**Does this PR …
> [APM-730] css fix for variables pop-up

- resources/i18n/ja.json
> Update Japanese translation

- projects/ama-sdk/src/lib/process-editor/cardview-properties/default-sequence-flow-item.model.ts
- projects/ama-sdk/src/lib/process-editor/properties.ts
- resources/i18n/en.json
- src/app/process-editor/process-editor.module.scss
- src/app/process-editor/process-editor.module.ts
- src/app/process-editor/services/bpmn-js/property-handlers/default-sequence-flow.handler.ts
- src/app/process-editor/services/bpmn-js/property-handlers/property.handlers.ts
- src/app/process-editor/services/bpmn/elements-properties.ts
- src/app/process-editor/services/cardview-properties/bpmn2CardView.ts
- src/app/process-editor/services/cardview-properties/default-sequence-flow-cardview-property.ts
- src/app/process-editor/services/cardview-properties/default-sequence-flow/default-sequence-flow-item.component.html
- src/app/process-editor/services/cardview-properties/default-sequence-flow/default-sequence-flow-item.component.scss
- src/app/process-editor/services/cardview-properties/default-sequence-flow/default-sequence-flow-item.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-729
Done
**Does this PR …
> [APM-279] Default Sequence Flow option

- package-lock.json
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/process-editor/process-editor.selectors.ts
- projects/ama-sdk/src/lib/schemas/properties.schema.ts
- resources/i18n/en.json
- src/app/process-editor/services/cardview-properties/implementation-item/implementation-item.component.html
- src/app/process-editor/services/cardview-properties/implementation-item/implementation-item.component.ts
- src/app/process-editor/store/process-entities.reducer.spec.ts
- src/app/process-editor/store/process-entities.reducer.ts
- src/app/process-editor/store/process.mock.ts
> - [] Tests for the changes have been added (for bug fixes / features)
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-738
fixed
**Does this PR …
> [APM-738] change json format for process mappings

- resources/i18n/ja.json
> Update ja translation

- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/ui-api-variation.ts
- projects/ama-sdk/src/lib/schemas/ui.schema.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-714
No more default value …
> [APM-714] fix for ui advanced editor

- projects/ama-sdk/src/lib/api-implementations/acm-api/project-api.ts
- projects/ama-sdk/src/lib/api/project-api.interface.ts
- resources/i18n/en.json
- src/app/dashboard/components/projects-list/projects-list.component.html
- src/app/dashboard/components/projects-list/projects-list.component.ts
- src/app/dashboard/services/dashboard.service.ts
- src/app/dashboard/store/actions/projects.ts
- src/app/dashboard/store/effects/projects.effects.spec.ts
- src/app/dashboard/store/effects/projects.effects.ts
- src/app/dashboard/store/reducers/dashboard.reducer.spec.ts
- src/app/dashboard/store/reducers/dashboard.reducer.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-240
Versioning …
> [APM-240] Versioning added for projects

- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/ui-api-variation.ts
- projects/ama-sdk/src/lib/schemas/ui.schema.ts
This reverts commit 910668428dadede2bd8ec923b46486cb8e16fb03.
> - [ ] Bugfix
> - [ ] Other... Please describe: Revert …
> Revert "fix for ui advanced editor (#60)"

- resources/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-810
New buttons renaming …
> [APM-810] changed New to NEW

- projects/ama-sdk/src/lib/ama-sdk.module.scss
- projects/ama-sdk/src/lib/code-editor/code-editor.module.scss
- projects/ama-sdk/src/lib/code-editor/code-editor.module.ts
- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.html
- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.scss
- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.spec.ts
- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.ts
- projects/ama-sdk/src/lib/code-editor/public_api.ts
- projects/ama-sdk/src/lib/code-editor/services/code-validator.service.spec.ts
- projects/ama-sdk/src/lib/code-editor/services/code-validator.service.ts
- projects/ama-sdk/src/lib/json-editor/json-editor.module.scss
- projects/ama-sdk/src/lib/variables/variables.component.html
- projects/ama-sdk/src/lib/variables/variables.component.scss
- projects/ama-sdk/src/lib/variables/variables.component.spec.ts
- projects/ama-sdk/src/lib/variables/variables.component.ts
- projects/ama-sdk/src/lib/variables/variables.module.ts
- projects/ama-sdk/src/public_api.ts
- resources/i18n/en.json
- src/app/connector-editor/components/connector-editor/connector-editor.component.html
- src/app/connector-editor/components/connector-editor/connector-editor.component.scss
- src/app/connector-editor/components/connector-editor/connector-editor.component.spec.ts
- src/app/connector-editor/components/connector-editor/connector-editor.component.ts
- src/app/connector-editor/connector-editor.module.ts
- src/app/process-editor/components/process-editor/process-editor.component.html
- src/app/process-editor/components/process-editor/process-editor.component.scss
- src/app/process-editor/components/process-editor/process-editor.component.spec.ts
- src/app/process-editor/components/process-editor/process-editor.component.ts
- src/app/process-editor/components/process-modeler/process-modeler.component.scss
- src/app/process-editor/components/process-modeler/process-modeler.component.ts
- src/app/process-editor/process-editor.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-756
Done
**Does this PR …
> [APM-756] General code editor

- package-lock.json
- projects/ama-sdk/src/lib/api/types.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-758
**Does this PR …
> [APM-758] changed mappings type

- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/connector-api-variation.ts
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/schemas/connector.schema.ts
- src/app/connector-editor/store/connector-entities.reducer.spec.ts
- src/app/connector-editor/store/connector-entities.reducer.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-755
done
**Does this PR …
> [APM-755] Removing ids from connector definitions

- package-lock.json
- src/app/dashboard/store/effects/projects.effects.ts
> - [x] Bugfix
> - [] Feature
https://issues.alfresco.com/jira/browse/APM-828
fixed
**Does this PR …
> [APM-828] sad path handling

- src/app/project-editor/components/project-navigation/project-navigation.component.html
- src/app/project-editor/components/project-navigation/project-navigation.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-829
Fixed
**Does this PR …
> [APM-829] New button css fix

- projects/ama-sdk/src/lib/variables/variables.component.html
- projects/ama-sdk/src/lib/variables/variables.component.scss
- resources/i18n/en.json
- src/app/process-editor/components/process-editor/process-editor.component.scss
- src/app/process-editor/components/process-modeler/process-modeler.component.scss
- src/app/process-editor/services/cardview-properties/process-variable-item/process-variable-item.component.html
- src/app/process-editor/services/cardview-properties/process-variable-item/process-variable-item.component.scss
- src/app/process-editor/services/cardview-properties/process-variable-item/process-variable-item.component.spec.ts
- src/app/process-editor/store/process-editor.effects.ts
> -  [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [] Tests for the changes have been added (for bug fixes / features)
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-759
**Does this PR …
> APM-758 extra requirements

- package-lock.json
- package.json
- projects/ama-sdk/package.json
Update ADF packages version 3.1.0-beta4
> Update ADF packages version 3.1.0-beta4

- .gitignore
- README.md
- angular.json
- config/proxy.conf.js
- docker-entrypoint.sh
- package-lock.json
- package.json
- projects/ama-sdk/src/lib/api-implementations/acm-api/request-api.helper.ts
- src/app.config.json
…pp.config.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-697
Done …
> [APM-697] Use .env with proxying to store host related information

- README.md
- docker-entrypoint.sh
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-840
Modified
**Does this PR …
> [APM-840] Modify API_URL to APP_CONFIG_BPM_HOST

- scripts/update-version.sh
> - [ ] Bugfix
> - [ ] Other... Please describe: tehnical
https://issues.alfresco.com/jira/browse/APM-838
updated …
> APM-838 update-version script

- resources/i18n/en.json
- src/app/process-editor/components/process-properties/process-properties.component.html
- src/app/project-editor/components/upload-file-button/upload-file-button.component.html
> - [ ] Bugfix
> - [x] Code style update (formatting, local variables)
https://issues.alfresco.com/jira/browse/APM-835
new translation strings …
> APM-835 new translation strings

- e2e/pages/connector-content.page.ts
- e2e/tests/connector/update-connector.e2e.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/decision-table-api-variations.ts
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.ts
- projects/ama-sdk/src/lib/helpers/public_api.ts
- projects/ama-sdk/src/lib/helpers/utils/create-entries-names.ts
- projects/ama-sdk/src/lib/helpers/utils/empty-decision-table.ts
- src/app/connector-editor/components/connector-editor/connector-editor.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-815
done
**Does this PR …
> [APM-815] Decision table new editor

- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/schemas/connector.schema.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-852
update schema connector …
> [APM-852] update schema connector to be able do add template properties

- src/app/connector-editor/store/connector-entities.reducer.spec.ts
- src/app/connector-editor/store/connector-entities.reducer.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-877
fixed
**Does this PR …
> [APM-877] Connector entity reducer fix

- projects/ama-sdk/src/lib/helpers/utils/empty-decision-table.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-854
fixed
**Does this PR …
> [APM-854] Dirty state fix for decision tables

- package-lock.json
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
- src/app/connector-editor/store/connector-editor.actions.ts
- src/app/connector-editor/store/connector-editor.effects.spec.ts
- src/app/connector-editor/store/connector-editor.effects.ts
- src/app/process-editor/store/process-editor.actions.ts
- src/app/process-editor/store/process-editor.effects.spec.ts
- src/app/process-editor/store/process-editor.effects.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-858
Create action and …
> [APM-858] create action and effects changes for Connector and Process

- projects/ama-sdk/src/lib/api-implementations/acm-api/model-api.ts
- projects/ama-sdk/src/lib/schemas/connector.schema.ts
- src/app/connector-editor/extension/connectors-filter.data-adapter.spec.ts
- src/app/connector-editor/extension/connectors-filter.data-adapter.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-857
done
**Does this PR …
> [APM-857] Filter connector list

- projects/ama-testing/src/e2e/pages/process-properties.card.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e page object updates
**Does this PR introduce a breaking change?** …
> Add missing methods in process properties card page

- projects/ama-sdk/src/lib/connector-editor/connector-editor.actions.ts
- projects/ama-sdk/src/lib/helpers/common.ts
- src/app/connector-editor/store/connector-editor.actions.ts
- src/app/connector-editor/store/connector-editor.effects.spec.ts
- src/app/connector-editor/store/connector-editor.effects.ts
- src/app/connector-editor/store/connector-entities.reducer.spec.ts
- src/app/connector-editor/store/connector-entities.reducer.ts
> - [ ] Bugfix
> - [x] Code style update (formatting, local variables)
https://issues.alfresco.com/jira/browse/APM-858
moved …
> [APM-858] moved CreateConnectorSuccessAction to ama-sdk

- src/app/process-editor/components/process-modeler/palette/palette.component.html
- src/app/process-editor/components/process-modeler/palette/palette.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-879
fixed
**Does this PR …
> [APM-879] Visual bug fix for process palette

- e2e/tests/login-logout/authorization.e2e.ts
- projects/ama-testing/src/e2e/pages/login-aps.page.ts
- src/app/app/host-settings/host-settings.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-856
fixed
**Does this PR …
> [APM-856] Session not active on login fixed

- src/app/process-editor/components/process-modeler/palette/palette-overlay.directive.ts
- src/app/process-editor/components/process-modeler/palette/palette.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-884
fixed
**Does this PR …
> [APM-884] connectors ui fix

- jest.config.js
- jest/transpile-es2015-modules-for-jest.js
- package-lock.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-843
fixed
**Does this PR …
> [APM-843] fix prod build

- package-lock.json
- projects/ama-testing/src/e2e/api/acm/models/form.ts
> - [ ] Bugfix
> - [ ] Other... Please describe: Add 'version' in formRepresentation when form is created
**Does this PR …
> [APM-883] Add 'version' in formRepresentation when form is created

- projects/ama-sdk/src/lib/helpers/utils/empty-decision-table.ts
- projects/ama-testing/src/e2e/api/acm/models/decision-table.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-886
done
**Does this PR …
> [APM-886] DT schema update

- projects/ama-sdk/src/lib/api-implementations/acm-api/form-definition.ts
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/schemas/form.schema.ts
> - [ x ] Bugfix
The form definition isn't correctly validate
The form definition is …
> review formDefinition fields

- projects/ama-testing/src/e2e/api/acm/models/form.ts
> - [ ] Bugfix
> - [ ] Other... Please describe: e2e 
export form e2e was failing
fixed
**Does this PR introduce a …
> APM-862 fix for forms e2e

- package-lock.json
- projects/ama-sdk/src/lib/api-implementations/acm-api/acm-api.module.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/acm-api.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/connector-api-variation.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/data-api-variation.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/decision-table-api-variations.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/form-api-variation.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/process-api-variation.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/ui-api-variation.ts
- projects/ama-sdk/src/lib/api/api.interface.ts
- projects/ama-sdk/src/lib/connector-editor/connector-editor.selectors.ts
- projects/ama-sdk/src/lib/process-editor/process-editor.selectors.ts
- projects/ama-sdk/src/lib/store/ama-store.module.ts
- projects/ama-sdk/src/lib/store/app.selectors.ts
- projects/ama-sdk/src/lib/store/entities.ts
- projects/ama-sdk/src/lib/store/entity.actions.ts
- projects/ama-sdk/src/lib/store/entity.selectors.ts
- projects/ama-sdk/src/lib/store/public_api.ts
- src/app/app-store.module.ts
- src/app/app.module.ts
- src/app/common/services/model-storage.service.ts
- src/app/connector-editor/connector-editor.module.ts
- src/app/connector-editor/extension/connectors-filter.data-adapter.ts
- src/app/connector-editor/router/guards/connectors-loader.guard.ts
- src/app/connector-editor/services/connector-editor.service.ts
- src/app/process-editor/process-editor.module.ts
- src/app/project-editor/router/guards/project-loader.guard.ts
- src/app/store/effects/entity.effects.ts
- src/app/store/reducers/entity.reducer.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-739
Implemented
**Does …
> [APM-739] First steps towards general model handling

- src/app/connector-editor/extension/connectors-filter.data-adapter.spec.ts
- src/app/connector-editor/extension/connectors-filter.data-adapter.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-924
commented filtering …
> [APM-924] show all connectors

- package-lock.json
- projects/ama-sdk/src/lib/helpers/utils/empty-decision-table.ts
- projects/ama-testing/src/e2e/api/acm/models/decision-table.ts
- projects/ama-testing/src/e2e/pages/code-editor.widget.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-922
Done.
**Does this …
> [APM-922] Initial decision table fix

- projects/ama-sdk/src/lib/variables/properties-viewer/properties-viewer.component.html
- projects/ama-sdk/src/lib/variables/properties-viewer/properties-viewer.component.scss
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-input.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/boolean-input.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/date-input.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/integer-input.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/string-input.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/value-type-inputs.mapping.ts
- projects/ama-sdk/src/lib/variables/variables.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-920
done
**Does this PR …
> [APM-920] Process variables type coercion

- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/process-editor/bpmn-element.ts
- projects/ama-sdk/src/lib/process-editor/cardview-properties/decision-task-item.model.ts
- projects/ama-sdk/src/lib/process-editor/properties.ts
- src/app/process-editor/i18n/en.json
- src/app/process-editor/process-editor.module.scss
- src/app/process-editor/process-editor.module.ts
- src/app/process-editor/services/bpmn-js/property-handlers/decisionTask.handler.ts
- src/app/process-editor/services/bpmn-js/property-handlers/property.handlers.ts
- src/app/process-editor/services/bpmn/elements-properties.ts
- src/app/process-editor/services/cardview-properties/bpmn2CardView.ts
- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.html
- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.scss
- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.ts
- src/app/process-editor/services/cardview-properties/decisionTask-cardview-property.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-893
First 2 tasks are done …
> [APM-925/926] Decision task in process editor

- projects/ama-testing/src/e2e/pages/code-editor.widget.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e tests fix
**Does this PR introduce a breaking change?** (check one …
> [APM-922] Fix update code editor method in e2e tests

- src/app/process-editor/services/bpmn/elements-properties.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-934
Fixed
**Does this PR …
> [APM-934] Boundary signal event fix

- src/app/app.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-932
fixed
**Does this PR …
> [APM-932] entities creation fix

- src/app/process-editor/components/process-editor/process-editor.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-288
fixed
**Does this PR …
> APM-288 fix monaco re-layouting issue for process editor

- projects/ama-sdk/src/lib/api-implementations/acm-api/project-api.ts
- projects/ama-sdk/src/lib/api/project-api.interface.ts
- projects/ama-sdk/src/lib/api/types.ts
- src/app/dashboard/services/dashboard.service.ts
- src/app/dashboard/store/actions/projects.ts
- src/app/dashboard/store/effects/projects.effects.spec.ts
- src/app/dashboard/store/effects/projects.effects.ts
- src/app/dashboard/store/reducers/dashboard.reducer.spec.ts
- src/app/dashboard/store/reducers/dashboard.reducer.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-937
fixed
**Does this PR …
> [APM-937] fix release bug

- projects/ama-sdk/src/lib/variables/properties-viewer/properties-viewer.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/integer-input.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-944
fixed
**Does this PR …
> [APM-944] Process var int type fix

- projects/ama-sdk/src/lib/variables/properties-viewer/properties-viewer.component.html
- projects/ama-sdk/src/lib/variables/properties-viewer/properties-viewer.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-input.component.ts
- projects/ama-sdk/src/lib/variables/properties-viewer/value-type-inputs/date-input.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-940
https://issues.alfresco.com/jira/browse/APM-946
**What …
> [APM-940] Process var date format fix

- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-950
fixed
**Does this PR …
> APM-950 fix process extension issue

- resources/i18n/en.json
- src/app/connector-editor/components/connector-header/connector-header.component.html
- src/app/connector-editor/components/connector-header/connector-header.component.ts
- src/app/connector-editor/components/connector-header/settings-dialog/connector-settings.dialog.component.html
- src/app/connector-editor/components/connector-header/settings-dialog/connector-settings.dialog.component.scss
- src/app/connector-editor/components/connector-header/settings-dialog/connector-settings.dialog.component.ts
- src/app/connector-editor/connector-editor.module.scss
- src/app/connector-editor/connector-editor.module.ts
- src/app/connector-editor/extension/connectors-filter.data-adapter.ts
- src/app/connector-editor/i18n/en.json
- src/app/connector-editor/store/connector-editor.actions.ts
- src/app/connector-editor/store/connector-editor.effects.spec.ts
- src/app/connector-editor/store/connector-editor.effects.ts
- src/app/store/actions/app.actions.ts
- src/app/store/effects/auth.effects.spec.ts
- src/app/store/effects/auth.effects.ts
- src/app/store/reducers/settings.reducer.spec.ts
- src/app/store/reducers/settings.reducer.ts
- src/app/store/selectors/settings.selectors.ts
- src/app/store/states/settings.state.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-892
added settings dialog …
> [APM-892] settings dialog for connectors

- e2e/tests/process/process-variables/create-process-variable.e2e.ts
- package-lock.json
- projects/ama-testing/src/e2e/pages/dialog/variables.dialog.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e test
**Does this PR introduce a breaking change?** (check one with …
> [APM-944] E2e - integer process variable value with invalid characters

- src/app/dashboard/components/projects-list/projects-list.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-948
fixed
**Does this PR …
> [APM-948] fix misaligned dashboard columns

- e2e/tests/process/process-variables/create-process-variable.e2e.ts
- package-lock.json
- projects/ama-testing/src/e2e/pages/calendar.ts
- projects/ama-testing/src/e2e/pages/dialog/variables.dialog.ts
- projects/ama-testing/src/e2e/pages/index.ts
- projects/ama-testing/src/e2e/util/date.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e test for process variables
**Does this PR introduce a breaking …
> [APM-940] E2e date process variable format

- src/app/dashboard/components/projects-list/projects-list.component.scss
- src/app/dashboard/store/reducers/dashboard.reducer.spec.ts
- src/app/dashboard/store/reducers/dashboard.reducer.ts
> - [ x] Tests for the changes have been added (for bug fixes / features)
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-935
fixed
**Does this PR …
> [APM-935] fix dashboard spinner

- src/app/process-editor/i18n/en.json
- src/app/process-editor/services/cardview-properties/signal-ref-item/signal-ref-item.component.html
- src/app/process-editor/services/cardview-properties/signal-ref-item/signal-ref-item.component.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-949
done
**Does this PR …
> [APM-949] signal name input

- package-lock.json
- src/app/dashboard/components/projects-list/projects-list.component.html
- src/app/dashboard/components/projects-list/projects-list.component.scss
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-953
Done
**Does this PR …
> Hide release button temporary

- projects/ama-sdk/src/lib/extension/connector-editor.ts
- resources/i18n/en.json
- src/app/connector-editor/connector-editor.module.ts
- src/app/project-editor/components/project-content/project-content.component.html
- src/app/project-editor/components/project-content/project-content.component.ts
- src/app/project-editor/components/project-settings/project-settings.component.html
- src/app/project-editor/components/project-settings/project-settings.component.scss
- src/app/project-editor/components/project-settings/project-settings.component.ts
- src/app/project-editor/project-editor.module.scss
- src/app/project-editor/project-editor.module.ts
- src/app/project-editor/store/effects/project.effects.spec.ts
- src/app/project-editor/store/effects/project.effects.ts
- src/app/project-editor/store/project-editor.actions.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-955
done
**Does this PR …
> [APM-955] Project settings dialog

- projects/ama-sdk/src/lib/api-implementations/acm-api/acm-api.module.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-api.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/model-variations/process-api-variation.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/process-api.ts
- projects/ama-sdk/src/lib/api/generalmodel-api.interface.ts
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/helpers/utils/createJsonBlob.ts
- projects/ama-sdk/src/lib/services/ama-services.module.ts
- projects/ama-sdk/src/lib/services/blob.service.ts
- projects/ama-sdk/src/lib/services/public_api.ts
- src/app/process-editor/components/process-header/process-header.component.spec.ts
- src/app/process-editor/components/process-header/process-header.component.ts
- src/app/process-editor/services/process-editor.service.ts
- src/app/process-editor/store/process-editor.actions.ts
- src/app/process-editor/store/process-editor.effects.ts
- src/app/project-editor/project-editor.module.ts
- src/app/project-editor/store/effects/project.effects.spec.ts
- src/app/project-editor/store/effects/project.effects.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-954
Done
**Does this PR …
> [APM-954] Add process-extension validation

- e2e/config/hooks/after-launch.js
- e2e/protractor.conf.js
- package-lock.json
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-testing/src/e2e/api/acm/models/process.ts
- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-962
Done
**Does this PR …
> [APM-962] Changed output mappings

- src/app/process-editor/components/process-editor/process-editor.component.scss
> - [x] Bugfix
> - [] Feature
https://issues.alfresco.com/jira/browse/APM-967
fixed
**Does this PR …
> [APM-967] fixed css bug for process properties

- e2e/resources/process/AMA_QA_UPLOADED_PROCESS.bpmn20.xml
- projects/ama-sdk/src/lib/helpers/utils/empty-diagram.ts
- projects/ama-testing/src/e2e/api/acm/models/process.ts
> - [] Bugfix
https://issues.alfresco.com/jira/browse/APM-956
new attribute was added …
> [APM-956] added new attribute to process definition in xml

- projects/ama-sdk/src/lib/variables/variables.component.scss
- src/app/dashboard/components/dahboard-navigation/dashboard-navigation.component.scss
- src/app/process-editor/store/process-variables.effects.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-941
https://issues.alfresco.com/jira/browse/APM-942
**What …
> [APM-941] Css fix

- projects/ama-sdk/src/lib/schemas/extensions.schema.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-950
fixed
**Does this PR …
> [APM-950] extensions schema fix

- src/app/process-editor/store/process-editor.actions.ts
- src/app/process-editor/store/process-editor.effects.ts
- src/app/process-editor/store/process-entities.reducer.spec.ts
- src/app/process-editor/store/process-entities.reducer.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-903
done
**Does this PR …
> [APM-903] Delete mapping for deleted service tasks

- src/app/process-editor/services/bpmn-js/property-handlers/priority.handler.spec.ts
- src/app/process-editor/services/bpmn-js/property-handlers/priority.handler.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-963
fixed
**Does this PR …
> [APM-963] fix priority handler

- projects/ama-sdk/src/lib/helpers/utils/create-entries-names.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-965
added …
> [APM-965] getRandomCharsAndNums method in ama-sdk

- e2e/tests/connector/list-connectors.e2e.ts
- projects/ama-sdk/src/lib/api-implementations/acm-api/project-api.ts
- projects/ama-sdk/src/lib/api/project-api.interface.ts
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-testing/src/e2e/api/acm/project.ts
- src/app/dashboard/components/projects-list/projects-list.component.html
- src/app/dashboard/components/projects-list/projects-list.component.scss
- src/app/dashboard/components/projects-list/projects-list.component.ts
- src/app/dashboard/dashboard.module.ts
- src/app/dashboard/router/guards/projects-loader.guard.ts
- src/app/dashboard/services/dashboard.service.ts
- src/app/dashboard/store/actions/projects.ts
- src/app/dashboard/store/effects/projects.effects.ts
- src/app/dashboard/store/reducers/dashboard.reducer.spec.ts
- src/app/dashboard/store/reducers/dashboard.reducer.ts
- src/app/dashboard/store/selectors/dashboard.selectors.ts
- src/app/dashboard/store/state/dashboard.state.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-958
done
**Does this PR …
> [APM-958] Pagination for project list

- src/app/process-editor/services/bpmn/elements-properties.ts
- src/app/process-editor/services/cardview-properties/expression-cardview-property.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1019
fixed
**Does this PR …
> [APM-1019] SequenceFlow bug fixed

- Jenkinsfile
- charts/activiti-modeling-app/Makefile
jx pipeline version bump workaround
> bump package.json version with sed

- src/app/process-editor/store/process-editor.effects.ts
- src/app/process-editor/store/process-entities.reducer.ts
> - [] Tests for the changes have been added (for bug fixes / features)
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1019
fixed
**Does this PR …
> [APM-1019] process editor bug fix

- src/app/process-editor/i18n/en.json
- src/app/process-editor/services/cardview-properties/process-name-cardview-property.ts
- src/app/process-editor/services/cardview-properties/validators/card-view-process-name.validator.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1039
added validator for …
> [APM-1039] added validator for process name card view

- package-lock.json
- projects/ama-sdk/src/lib/process-editor/bpmn-modeler.ts
- projects/ama-sdk/src/lib/process-editor/bpmn.d.ts
- src/app/process-editor/components/process-editor/process-editor.component.ts
- src/app/process-editor/components/process-modeler/process-modeler.component.spec.ts
- src/app/process-editor/components/process-modeler/process-modeler.component.ts
- src/app/process-editor/i18n/en.json
- src/app/process-editor/process-editor.module.ts
- src/app/process-editor/services/bpmn-factory.service.ts
- src/app/process-editor/services/process-loader.service.ts
- src/app/process-editor/services/process-modeler.service.ts
- src/app/process-editor/store/process-editor.reducer.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/APM-903 's comment.
Fixed …
> [APM-903][APM-1046] - Fix 'shape.remove' issue when reloading the xml

- package-lock.json
- projects/ama-testing/src/e2e/pages/common/generic.webelement.ts
- projects/ama-testing/src/e2e/pages/process-modeler.component.ts
- projects/ama-testing/src/e2e/pages/process-properties.card.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e test
**Does this PR introduce a breaking change?** (check one with …
> E2e Add decision table task

- src/app/process-editor/components/process-modeler/palette/palette.component.scss
> [APM-1058] change size pallet

- projects/ama-sdk/src/lib/process-editor/bpmn-element.ts
- resources/i18n/en.json
- src/app/process-editor/components/process-modeler/process-modeler-bpmnjs.component.scss
- src/app/process-editor/config/palette-elements.json.ts
- src/app/process-editor/services/bpmn/elements-properties.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1059
Added sub process as a …
> [APM-1059] added subprocess

- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.html
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.spec.ts
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1044
https://issues.alfresco.com/jira/browse/APM-1045 …
> APM-1044 fix duplication of entries created with enter

- package-lock.json
- package.json
- projects/ama-sdk/package.json
- scripts/update-version.sh
> Update adf and js-api version 3.3.0-beta4

- e2e/protractor.conf.js
- e2e/tests/process/create-process.e2e.ts
- e2e/tests/process/delete-process.e2e.ts
- e2e/tests/process/process-variables/create-process-variable.e2e.ts
- projects/ama-testing/src/e2e/api/acm/acm-backend.ts
- projects/ama-testing/src/e2e/pages/common/generic.page.ts
- projects/ama-testing/src/e2e/pages/login-aps.page.ts
- src/app.config.json
- src/app/app.module.ts
> - [ ] Bugfix
We used PathLocationStrategy (e.g.: /login).
See https://issues.alfresco.com/jira/browse/APM-1071 …
> [APM-1071] Use HashLocationStrategy in the application

- src/app/process-editor/components/process-editor/process-editor.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1075
fixed
**Does this PR …
> [APM-1075] Delete process bug fix

- Jenkinsfile
- e2e/tsconfig.e2e.json
- package-lock.json
- package.json
- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
- projects/ama-testing/src/e2e/api/acm/models/process.ts
- projects/ama-testing/src/e2e/util/index.ts
- projects/ama-testing/src/e2e/util/types.ts
- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.ts
- src/app/process-editor/store/process-entities.reducer.spec.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-1027
Implemented. …
> [APM-1027] Using names instead of ids in parameter mapping

- src/app/process-editor/components/process-editor/process-editor.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1017
fixed
**Does this PR …
> [APM-1017] Process xml editor fix

- package.json
> - [ ] Bugfix
> - [x] Documentation
https://issues.alfresco.com/jira/browse/APM-1049
done
**Does this PR …
> [APM-1049] Update license in package.json

- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.spec.ts
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1080
fixed
**Does this PR …
> [APM-1080] Create entity small fix

- e2e/tests/connector/list-connectors.e2e.ts
- package-lock.json
- projects/ama-testing/src/e2e/pages/dashboard.page.ts
- projects/ama-testing/src/e2e/pages/pagination.component.ts
- src/app/dashboard/components/projects-list/projects-list.component.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e tests fix
**Does this PR introduce a breaking change?** (check one …
> [APM-1072] Increase page size if project is not displayed on first page

- src/app/dashboard/components/releases-list/releases-list.component.html
- src/app/dashboard/components/releases-list/releases-list.component.scss
- src/app/dashboard/components/releases-list/releases-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1088
fixed
**Does this PR …
> APM-1088 fix release list and rebase

- projects/ama-sdk/src/lib/helpers/common.ts
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.html
- projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
- projects/ama-sdk/src/lib/interfaces/model-creator.interface.ts
- resources/i18n/en.json
- src/app/connector-editor/extension/connector-creator.extension.ts
- src/app/dashboard/components/dahboard-navigation/dashboard-navigation.component.ts
- src/app/dashboard/components/projects-list/projects-list.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1052
done
**Does this PR …
> [APM-1052] User friendly validation messages

- package-lock.json
- package.json
> - [ ] Bugfix
> - [x] Other... Please describe: e2e runner
**Does this PR introduce a breaking change?** (check one …
> [APM-897] Run e2e without building dev server

- resources/i18n/en.json
- src/app/process-editor/store/process-editor.effects.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1082
fixed
**Does this PR …
> APM-1082 empty name error added

- e2e/tests/project/delete-project.e2e.ts
- e2e/tests/project/export-project.e2e.ts
- e2e/tests/project/update-project.e2e.ts
- package-lock.json
- projects/ama-testing/src/e2e/pages/common/generic.webelement.ts
- projects/ama-testing/src/e2e/pages/dashboard.page.ts
- projects/ama-testing/src/e2e/pages/login-aps.page.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e fix
**Does this PR introduce a breaking change?** (check one with …
> [E2e fix] Find project in list with page navigation

- e2e/test.config.ts
- projects/ama-testing/src/e2e/api/acm/project.ts
- projects/ama-testing/src/e2e/api/api.interfaces.ts
- projects/ama-testing/src/e2e/pages/dashboard.page.ts
- projects/ama-testing/src/e2e/pages/snackbar.ts
- src/app/dashboard/components/projects-list/projects-list.component.html
- src/app/dashboard/components/releases-list/releases-list.component.html
> - [ ] Bugfix
e2e
https://issues.alfresco.com/jira/browse/APM-1001
done
**Does this …
> [APM-1023] Project release e2e tests

- projects/ama-sdk/src/lib/api/types.ts
- projects/ama-sdk/src/lib/schemas/form.schema.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1094?workflowName=ADF&stepId=1
**What is the new …
> [APM-1094] Add standAlone property to schema and FormDefinition

- package-lock.json
- projects/ama-testing/src/e2e/pages/login-aps.page.ts
- src/app.config.json
> - [ ] Bugfix
> - [x] Other... Please describe: E2e fix
**Does this PR introduce a breaking change?** (check one with …
> [APM-1125] Disable implicit flow for e2e

- projects/ama-sdk/src/lib/schemas/form.schema.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1120
changed form schema to …
> [APM-1120] changed form schema

- e2e/tests/project/upload-project.e2e.ts
- package-lock.json
- projects/ama-testing/src/e2e/api/acm/project.ts
- projects/ama-testing/src/e2e/api/api.interfaces.ts
* Add e2e test for import project using the rest api
> - [ ] Bugfix
> - [x] Other... Please describe: E2e add import project using the api
**What is …
> [APM-1116] E2e Add import project api call

- e2e/tests/process/create-process.e2e.ts
- projects/ama-sdk/src/lib/process-editor/process-editor.selectors.ts
- src/app/process-editor/i18n/en.json
- src/app/process-editor/process-editor.module.scss
- src/app/process-editor/process-editor.module.ts
- src/app/process-editor/services/cardview-properties/called-element-item/called-element-item.component.html
- src/app/process-editor/services/cardview-properties/called-element-item/called-element-item.component.scss
- src/app/process-editor/services/cardview-properties/called-element-item/called-element-item.component.ts
- src/app/process-editor/services/cardview-properties/called-element-item/called-element-item.model.ts
- src/app/process-editor/store/process-editor.effects.ts
- src/app/process-editor/store/process-editor.selectors.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1097
done
**Does this PR …
> [APM-1097] Variable mapping - Subprocesses (call activity)

- projects/ama-testing/src/e2e/pages/common/generic.webelement.ts
> [APM-1122]Add drag and drop method for not clickable elements

- .gitignore
- .travis.yml
- package-lock.json
- package.json
- scripts/build-pipeline/pr-branch-finder.js
- scripts/build-pipeline/update-enterprise.sh
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-727
Done
**Does this PR …
> [APM-727] Notify other repos when a new tag of this repo was created

- Jenkinsfile
- package.json
> Almerico jenkins memory issue

- projects/ama-sdk/src/lib/schemas/connector.schema.ts
- projects/ama-sdk/src/lib/schemas/form.schema.ts
- projects/ama-sdk/src/lib/schemas/ui.schema.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1130
**Does this PR …
> [APM-1130] - add posibility to add visibilityCondition to header

- projects/ama-sdk/src/lib/schemas/connector.schema.ts
- projects/ama-sdk/src/lib/schemas/ui.schema.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1143
**Does this PR …
> [APM-1143] - add schema pattern validation

- src/app/process-editor/services/cardview-properties/decision-task-item/decision-task-item.component.ts
- src/app/process-editor/services/cardview-properties/implementation-item/implementation-item.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1141 …
> [APM-1141] Implement OnDestroy correctly to prevent memory leaks

- projects/ama-testing/src/e2e/pages/dialog/variables.dialog.ts
> [APM-1118] add a new method for form variable

- package-lock.json
- package.json
- projects/ama-sdk/package.json
> [APM-1156] - Update modeler app to use right ADF version

- package-lock.json
- src/app/process-editor/store/process-entities.reducer.spec.ts
- src/app/process-editor/store/process-entities.reducer.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1144
fixed
**Does this PR …
> [APM-1144] Process entities reducer fix

- src/app/dashboard/store/effects/projects.effects.spec.ts
- src/app/dashboard/store/effects/projects.effects.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1182
fixed
**Does this PR …
> [APM-1182] change log error message for failed releases

- package-lock.json
- package.json
- projects/ama-sdk/package.json
> Update ADF packages version 3.4.0-beta8

- e2e/tests/process/create-process.e2e.ts
- src/app/process-editor/services/cardview-properties/called-element-item/called-element-item.component.html
- src/app/process-editor/services/cardview-properties/called-element-item/called-element-item.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1153
fixed
**Does this PR …
> [APM-1153] Process prefix added for callActivity

- package-lock.json
- src/app/dashboard/components/projects-list/projects-list.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1157
**Does this PR …
> [APM-1157] - fix see releases option

- cspell.json
- e2e/tests/log-history/log-history.e2e.ts
- projects/ama-sdk/src/lib/helpers/components/editor-footer/editor-footer.component.html
- projects/ama-testing/src/e2e/pages/index.ts
- projects/ama-testing/src/e2e/pages/log-history.page.ts
- projects/ama-testing/src/e2e/pages/process-content.page.ts
- src/app/app/app-layout/editor-footer/editor-footer.component.html
> [APM-1172]Add tests for error messages in log history.

- cspell.json
- e2e/tests/process/create-process.e2e.ts
- projects/ama-testing/src/e2e/pages/dialog/index.ts
- projects/ama-testing/src/e2e/pages/dialog/process-validation.dialog.ts
- projects/ama-testing/src/e2e/pages/index.ts
- projects/ama-testing/src/e2e/pages/task-properties.card.ts
> [APM-1171] add tests for user task validation (assignee, candidateUsers, candidateGroups)

- angular.json
- e2e/app.config.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1179
**Does this PR …
> [APM-1179] - fix broken session

- projects/ama-sdk/src/lib/process-editor/bpmn-element.ts
- src/app/process-editor/components/process-modeler/process-modeler-bpmnjs.component.scss
- src/app/process-editor/services/activiti.json
- src/app/process-editor/services/bpmn/elements-properties.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1126
Inclusive gateways are …
> [APM-1126] Add BPMN Inclusive Gateways to Process Modeler

- e2e/tests/process/create-process.e2e.ts
- projects/ama-testing/src/e2e/pages/dialog/process-validation.dialog.ts
- projects/ama-testing/src/e2e/pages/log-history.page.ts
- projects/ama-testing/src/e2e/pages/process-modeler.component.ts
- projects/ama-testing/src/e2e/pages/snackbar.ts
> [APM-1193] fix import for log-history.page

- projects/ama-sdk/src/lib/schemas/form.schema.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1195
fixed
**Does this PR …
> [APM-1195] changed form schema

- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.spec.ts
- projects/ama-sdk/src/lib/code-editor/components/code-editor/code-editor.component.ts
> - [x] Bugfix
fixed
https://issues.alfresco.com/jira/browse/APM-1180
**Does this PR …
> [APM-1180] fix xml editor issue with jumping cursor

- projects/ama-testing/src/e2e/api/acm/models/form.ts
> - [ ] Bugfix
Adding the standalone flag to be used when creating forms using the API call
**What is the new …
> [APM-1106] Adding the standalone flag for API call

- e2e/tests/process/process-variables/create-process-variable.e2e.ts
- projects/ama-sdk/src/lib/variables/variables.component.html
- projects/ama-sdk/src/lib/variables/variables.component.scss
- projects/ama-sdk/src/lib/variables/variables.component.ts
- projects/ama-testing/src/e2e/pages/dialog/variables.dialog.ts
- src/app/process-editor/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1151
**Does this PR …
> [APM-1151] - Remove json editor from variable dialog.
